# ============================================
# CONFIGURAÇÃO DO POSTGRESQL - NEON.TECH (NUVEM)
# ============================================
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# CONFIGURAÇÃO DO HIBERNATE/JPA
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Ocultar SQL em produção para evitar logs gigantes
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Otimizações de performance (Batching)
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true